### ISSUE TITLE
5명 수강 리스트를 이용하여 데이터 정형화

### ISSUE THREAD

**Issue by Cr28self** [kakaoDreamy/jnu-eat#18]
- [ ] 5명 수강 리스트 데이터 받아오기
- [ ] 받은 데이터를 엑셀에다가 정형화

**Comment by Cr28self** [comment]
- [ ] 5명 수강 리스트 데이터 받아오기
- [ ] 받은 데이터를 엑셀에다가 정형화

**Comment by kimmjae99** [comment]
프로젝트 변경으로 인한 이슈 삭제
