### ISSUE TITLE
룰렛 결과가 하나 남았을 때도 룰렛이 돌아가는 현상

### ISSUE THREAD

**Issue by Deutan99** [kakaoDreamy/jnu-eat#38]
룰렛 결과가 두 개 남을 시 별로에요 눌렀을 시 화면이 넘어가야 할 것 같습니다.
별로에요 누르면 -> 마지막 선택지에 해당하는 식당 지도 화면으로 이동

**Comment by Cr28self** [comment]
룰렛 결과가 두 개 남을 시 별로에요 눌렀을 시 화면 넘어가는거 기능 추가했습니다..
